### ISSUE TITLE
After npm run production nothing happens

### ISSUE THREAD

**Issue by DanilBorchevkin** [metricio/metricio#16]
In dev mode all works but on the target server (Google Compute Engine, f1-micro - 1CPU 0.6Gb RAM, Ubuntu 18.04) after run

`npm run production`

I see in the console only 

```
> metricio@1.2.0 production /home/danil_borchevkin/web_electricmeter
> cross-env NODE_ENV=production webpack -p && NODE_ENV=production babel-node app.js
```

Ports doesn't open, nothing to happens.

Why I can try to resolve this situation?

**Comment by DanilBorchevkin** [comment]
Upd. 
After 5-10 minutes I got following:

```
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^
Error: ENOENT: no such file or directory, scandir '/home/danil_borchevkin/web_electricmeter/src/jobs'
    at Object.fs.readdirSync (fs.js:904:18)
    at requireAll (/home/danil_borchevkin/web_electricmeter/node_modules/require-all/index.js:32:18)
    at Object.<anonymous> (/home/danil_borchevkin/web_electricmeter/lib/jobs.js:14:14)
    at Module._compile (module.js:652:30)
    at loader (/home/danil_borchevkin/web_electricmeter/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/danil_borchevkin/web_electricmeter/node_mod
ules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/danil_borchevkin/web_electricmeter/app.js:13:1)
    at Module._compile (module.js:652:30)
    at loader (/home/danil_borchevkin/web_electricmeter/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/danil_borchevkin/web_electricmeter/node_mod
ules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metricio@1.2.0 production: `cross-env NODE_ENV=production webpack -p && NODE_ENV=production babel-node a
pp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the metricio@1.2.0 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/danil_borchevkin/.npm/_logs/2018-05-27T21_59_02_284Z-debug.log
```
__________________________________________________________________
Data from log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'production' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'preproduction', 'production', 'postproduction' ]
5 info lifecycle metricio@1.2.0~preproduction: metricio@1.2.0
6 info lifecycle metricio@1.2.0~production: metricio@1.2.0
7 verbose lifecycle metricio@1.2.0~production: unsafe-perm in lifecycle true
8 verbose lifecycle metricio@1.2.0~production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gy
p-bin:/home/danil_borchevkin/web_electricmeter/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
n:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle metricio@1.2.0~production: CWD: /home/danil_borchevkin/web_electricmeter
10 silly lifecycle metricio@1.2.0~production: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production webpack -p && NODE_ENV=production babel-node app.js' ]
11 silly lifecycle metricio@1.2.0~production: Returned: code: 1  signal: null
12 info lifecycle metricio@1.2.0~production: Failed to exec production script
13 verbose stack Error: metricio@1.2.0 production: `cross-env NODE_ENV=production webpack -p && NODE_ENV=producti
on babel-node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:2
85:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.
js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid metricio@1.2.0
15 verbose cwd /home/danil_borchevkin/web_electricmeter
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "production"
16 verbose Linux 4.15.0-1008-gcp
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "production"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error metricio@1.2.0 production: `cross-env NODE_ENV=production webpack -p && NODE_ENV=production babel-node app.js`
22 error Exit status 1
23 error Failed at the metricio@1.2.0 production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by DanilBorchevkin** [comment]
upd. Sorry, it doesn't working on dev too

**Comment by DanilBorchevkin** [comment]
I figure out this issue. Soory it's my mistake - something happen and I really don't have on the target server jobs folder.
