### ISSUE TITLE
v1.2.0 Start Script Failure

### ISSUE THREAD

**Issue by eduardoRubioG** [metricio/metricio#27]
Hello 👋 

Working on a MacOS 10.14.5 and after a clean download of Metricio (downloaded the latest zip)  I am having issues when running: 
```
npm i && npm run start
```

Specifically, I am getting this: 
```
> metricio@1.2.0 start /Users/erubioteruel/Documents/GitHub/DevOps-Dashboard
> babel-node app.js

/Users/erubioteruel/Documents/GitHub/DevOps-Dashboard/app.js:1
import { createServer } from 'http';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at loader (/Users/erubioteruel/Documents/GitHub/DevOps-Dashboard/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/erubioteruel/Documents/GitHub/DevOps-Dashboard/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at Object.<anonymous> (/Users/erubioteruel/Documents/GitHub/DevOps-Dashboard/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metricio@1.2.0 start: `babel-node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the metricio@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erubioteruel/.npm/_logs/2019-07-23T16_56_42_601Z-debug.log
```

I thought it might be because I had not installed Redis, but I went ahead and did that but I am still getting the same message. 

Any help would be appreciated!!

**Comment by eduardoRubioG** [comment]
Also, in case this helps: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle metricio@1.2.0~prestart: metricio@1.2.0
6 info lifecycle metricio@1.2.0~start: metricio@1.2.0
7 verbose lifecycle metricio@1.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle metricio@1.2.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/erubioteruel/Documents/GitHub/DevOps-Dashboard/node_modules/.bin:/usr/share/www/intranet.directstartv.com/scripts/srcsync-dir:/usr/local/bin:/usr/share/www/devops/scripts:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/share/www/intranet.directstartv.com/scripts/srcsync-dir:/usr/share/www/devops/scripts
9 verbose lifecycle metricio@1.2.0~start: CWD: /Users/erubioteruel/Documents/GitHub/DevOps-Dashboard
10 silly lifecycle metricio@1.2.0~start: Args: [ '-c', 'babel-node app.js' ]
11 silly lifecycle metricio@1.2.0~start: Returned: code: 1  signal: null
12 info lifecycle metricio@1.2.0~start: Failed to exec start script
13 verbose stack Error: metricio@1.2.0 start: `babel-node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid metricio@1.2.0
15 verbose cwd /Users/erubioteruel/Documents/GitHub/DevOps-Dashboard
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error metricio@1.2.0 start: `babel-node app.js`
22 error Exit status 1
23 error Failed at the metricio@1.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jordanfitnext** [comment]
@eduardoRubioG this one works for me : https://stackoverflow.com/a/33608835/3506156
